modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Jun1devs/MeowAuth/issues"

[[mods]]
modId = "meowauth_server"
version = "${mod_version}"
displayName = "${mod_name} Server"
#updateJSONURL="https://example.com/updates.json"
displayURL = "https://github.com/Jun1devs/MeowAuth"
logoFile = "meowauth_logo.png"
logoBlur = false
credits = "Jun1devs Team"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.meowauth_server]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.meowauth_server]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.meowauth_server]]
modId = "meowlib"
mandatory = false
versionRange = "[1.0,)"
ordering = "AFTER"
side = "SERVER"
